### ISSUE TITLE
postproc bombs on df_lines.node

### ISSUE THREAD

**Issue by pjuckem** [aleaf/SFRmaker#89]
postproc bombs on write_streamflow_shp on line 1379 due to hard-coded 'node' attribute.  (geom_idx = ...)

``` python
            if df_lines[node_col].dtype.name == 'object':
                raise TypeError('Node number column of shapefile is not numeric!')

            # first assign geometries for model cells with only 1 SFR reach
            df_lines_geoms = df_lines.geometry.values
            geom_idx = [df_lines.index[df_lines.node == n] for n in df.node.values]
            df['geometry'] = [df_lines_geoms[g[0]] if len(g) == 1 else LineString() for g in geom_idx]
```

**Comment by aleaf** [comment]
Paul, I think I've fixed this. Try pulling from the renumbering fix branch and see if it'll work on your model. I added a new method for the fix, **segment_reach2linework_shapefile()**, which assigns geometries from a shapefile of the exploded linework using intersections with other geometries (coincident starts/ends). The problem becomes a little messy when there are multiple cells with collocated reaches that are adjacent. But, the method can iterate, so that the reaches are first matched up for collocated cells adjacent to cells with only one reach; once those are matched then the next cell over with collocated reaches can be matched with geometries, and so on. See the doc string for more info. I've set up the **write_streamflow_shapefile()** method to call **segment_reach2linework_shapefile()** if it doesn't find segment and reach information in the linework shapefile, so there's no need to run it separately. However, you can speed up subsequent runs of  **write_streamflow_shapefile()** by supplying the new linework shapefile that has segment and reach information (written by  **segment_reach2linework_shapefile()**). Then the geometries are assigned directly; if the segments and reaches in the SFR output and the linework shapefile aren't identical, it will throw an error.

A better fix for this is to simply write a linework shapefile with segment and reach information when Mat1 is written for the first time. I will implement this when I build the SFR package for the Bad River GSFLOW model.

**Comment by pjuckem** [comment]
Thanks Andy.
I'll try this.
As you pursue your plan to write linework when writing MAT1, I assume
you're already planning for users that will invoke the RenumberSegments
method.....

Thanks for all your work on this!
Paul
