### ISSUE TITLE
gisutils  pyproj.Transformer error

### ISSUE THREAD

**Issue by hwreeves-USGS** [aleaf/SFRmaker#95]
Andy - I built gisutils using the environment made with requirements.yml as you suggest, and I did the same with sfrmaker.  But I keep getting an error on pyproj.Transformer

f:\projects\gis-utils\gisutils\project.py in project(geom, projection1, projection2)
     47     # pyproj 2 style
     48     # https://pyproj4.github.io/pyproj/dev/gotchas.html
---> 49     transformer = pyproj.Transformer.from_crs(projection1, projection2, always_xy=True)
     50 
     51     # check for x, y values instead of shapely objects

AttributeError: module 'pyproj' has no attribute 'Transformer'

The environment asks for pyproj > 2.0; but maybe that isn't what the base environment is using - have you seen this problem and do you have any suggestions?  Thanks-

**Comment by aleaf** [comment]
Hi @hwreeves-USGS, I'm guessing that you are using an earlier version of pyproj (< 2.0). If you look at that gotchas link above, it has more details on changes that were made with pyproj 2, which reflect major changes to the underlying PROJ library. In short, it's not going back, so you should upgrade pyproj 2. I decided to just ditch support for older pyproj versions in gisutils, because it's easy to upgrade, and sfrmaker also now uses some new functionality in pyproj to more robustly compare CRS, when deciding whether reprojection is needed.

**Comment by hwreeves-USGS** [comment]
Thanks Andy - I've got to figure out environments. For some reason it looks like I have
both pyproj 1.9 something and pyproj 2. something installed.  My sfrmaker environment
works, but I it doesn't have jupyter - I guess I could add that to the environment - and I
am having trouble updating my conda base environment with the updated pyproj.

HWR


Howard W. Reeves
Groundwater and Watershed Modeling Team Lead
USGS Upper Midwest Water Science Center
5840 Enterprise Drive
Lansing, Michigan 48911
517-887-8914
________________________________

**Comment by hwreeves-USGS** [comment]
I was finally able to remove pyproj 1.9.6 from my base install, `conda install` kept wanting to put pyproj 1.9.6 and asking for a later version didn't work.  I used pip to install pyproj and geopandas and now things are working.

**Comment by aleaf** [comment]
It might be easiest to just do a [clean uninstall](https://docs.anaconda.com/anaconda/install/uninstall/) of Anaconda and then remake any environments you need. In general, I think it's best to work in environments and not use the base environment. That way, it's easy to blow an environment away and rebuild it from a yml file if you need to. The conda package solver seems to struggle after a while with successive updates and new package installs.

I mostly work in an environment that has all of the packages I use (defined in a yml file), and then have some other environments for testing (especially when different versions of python or numpy, etc. are required). I had to recreate it yesterday, because I needed to upgrade pytest, but conda wanted to upgrade or downgrade dozens of other packages. Other times, there are unresolvable version conflicts. Usually, thats a sign that it's time to remake it.
