### ISSUE TITLE
Full paths in SFR file

### ISSUE THREAD

**Issue by mnfienen** [aleaf/sfrmaker#99]
Creating an `sfrdata` object using a script, the paths to output files (`cbc`, etc.) in the sfr file as written with `sfrdata.write_package()` have fully qualified paths rather than relative paths.

**Comment by aleaf** [comment]
@mnfienen not saying that it should have this behavior, but looking at the code, I think this might be happening because you are providing an absolute path for the sfr package filename, or, for some reason, the filename of the attached flopy.ModflowSfr2 instance is absolute (if no filename is supplied to SFRData.write_package, `self.modflow_sfr2.fn_path` is used). Options for the options block can be specified as a list of strings; if no options are given, then filename for the sfr package is used for the FILEOUT entries.
